package com.codepilot1c.core.edt.runtime;

/**
 * Stable error codes for EDT runtime tools.
 */
public enum EdtToolErrorCode {
    INVALID_ARGUMENT,
    INVALID_PATH,
    PRIMARY_EXISTS,
    NAME_COLLISION,
    PATH_ALREADY_ASSOCIATED_AS,
    EDT_NOT_READY,
    EDT_SERVICE_UNAVAILABLE,
    EDT_AUTH_REQUIRED,
    EDT_INFOBASE_LOCKED,
    PROJECT_NOT_FOUND,
    PROJECT_ALREADY_EXISTS,
    INFOBASE_ASSOCIATION_NOT_FOUND,
    INFOBASE_NOT_FOUND,
    LAUNCH_CONFIG_NOT_FOUND,
    RUNTIME_VERSION_NOT_FOUND,
    RUNTIME_NOT_RESOLVED,
    STANDALONE_SERVER_UNAVAILABLE,
    STANDALONE_RUNTIME_NOT_FOUND,
    STANDALONE_SERVER_CREATE_FAILED,
    STANDALONE_SERVER_START_FAILED,
    CONFIG_EXPORT_FAILED,
    PROJECT_IMPORT_FAILED,
    UPDATE_FAILED,
    IB_LOCKED,
    PROCESS_START_FAILED,
    PROCESS_TIMEOUT,
    UPDATE_BLOCKED_BY_HTTP_CLIENTS,
    UPDATE_BLOCKED_BY_WEBSERVER,
    WEB_SERVER_NOT_FOUND,
    WEB_SERVER_EXISTS,
    WEB_SERVER_ACCESS_FAILED,
    PUBLICATION_NOT_FOUND,
    WEB_EXTENSION_NOT_FOUND,
    WEB_SERVER_RESTART_FAILED,
    PROBE_FAILED
}
