package com.codepilot1c.core.edt.runtime;

/**
 * Stable error codes for EDT runtime tools.
 */
public enum EdtToolErrorCode {
    INVALID_ARGUMENT,
    INVALID_PATH,
    PRIMARY_EXISTS,
    EDT_NOT_READY,
    EDT_SERVICE_UNAVAILABLE,
    PROJECT_NOT_FOUND,
    PROJECT_ALREADY_EXISTS,
    INFOBASE_ASSOCIATION_NOT_FOUND,
    INFOBASE_NOT_FOUND,
    LAUNCH_CONFIG_NOT_FOUND,
    RUNTIME_VERSION_NOT_FOUND,
    RUNTIME_NOT_RESOLVED,
    STANDALONE_SERVER_UNAVAILABLE,
    STANDALONE_RUNTIME_NOT_FOUND,
    STANDALONE_SERVER_CREATE_FAILED,
    STANDALONE_SERVER_START_FAILED,
    CONFIG_EXPORT_FAILED,
    PROJECT_IMPORT_FAILED,
    UPDATE_FAILED,
    PROCESS_START_FAILED,
    PROCESS_TIMEOUT
}
